spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        ddl-auto: none
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  flyway:
    enabled: true # Flyway 활성화
    locations: classpath:db/migration # 마이그레이션 SQL 경로
    baseline-on-migrate: true # Flyway를 처음 실행할 때 필요 -> Baseline 기록
    baseline-version: 20250925_1530
    validate-on-migrate: true # SQL 변조/누락 방지
    clean-disabled: true # 스키마 초기화 금지
    
lock:
  redis:
    registry-key: "course-service:regist-course"
    expired-ms: 10000

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus